version : "3"

services :
  mysql :
    image : mysql:8.0
    container_name : mysql
    command : --default-authentication-plugin=mysql_native_password
    restart : unless-stopped
    env_file : .env
    ports :
      - '3306:3306'
    volumes :
      - db-data:/var/lib/mysql
    networks :
      - net

  web :
    container_name : web
    image : nginx:1.17.4-alpine
    restart : unless-stopped
    ports :
      - '80:80'
      - '443:443'
    networks :
      - net
    volumes :
      - ./log/web/:/var/log/nginx
      - ./html:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    depends_on :
      - mysql

  drupal :
    image : drupal:8.7.8-fpm-alpine
    container_name : drupal
    depends_on :
      - mysql
    restart : unless-stopped
    networks :
      - net
    volumes :
      - ./log/drupal/:/var/log
      - ./html:/var/www/html
#
#  certbot :
#    depends_on :
#      - web
#    image : certbot/certbot
#    container_name : certbot
#    volumes :
#      - ./log/certbot/:/var/log
#      - certbot-etc:/etc/letsencrypt
#      - ./html:/var/www/html
#    #      - drupal-data:/var/www/html
#    command : certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --force-renewal -d your_domain -d www.your_domain
#    networks :
#      - net

networks :
  net :
    driver : bridge

volumes :
  drupal-data :
  db-data :
  certbot-etc :